
theme: jekyll-theme-minimal

title: The Programmable Data Plane Reading List
authors: Oliver Michel, Gábor Rétvári, Roberto Bifulco, Stefan Schmid

nav:
  - text: Architectures
    url: /architectures/
  - text: Abstractions
    url: /abstractions/
  - text: Algorithms & HW Realizations
    url: /algorithms/
  - text: Applications
    url: /applications/
  - text: Miscellaneous Topics
    url: /misc/

baseurl: ''
url: https://programmabledataplanereview.github.io
markdown: kramdown

sass:
  style: compressed